# Available ruby versions: http://rubies.travis-ci.org/

language: ruby
rvm:
  - "2.4" # latest 2.4.x
  - "2.5" # latest 2.5.x
  - "2.6" # latest 2.6.x
  - "ruby-head"
script:
  - bundle exec rspec
  - bundle exec rubocop

before_install:
  - gem install bundler
  - gem install rspec
